apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: brewspace-frontend
  labels:
    app.kubernetes.io/name: brewspace-frontend
    app.kubernetes.io/part-of: brewspace
spec:
  to:
    kind: Service
    name: brewspace-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: brewspace-api
  labels:
    app.kubernetes.io/name: brewspace-api
    app.kubernetes.io/part-of: brewspace
spec:
  to:
    kind: Service
    name: brewspace-api
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
